### ISSUE TITLE
Does this include networking?

### ISSUE THREAD

**Issue by vr00n** [Enterprise-Group-Ltd/aws-services-snapshot#2]
Looks very promising. 
Does this snapshot include VPC, subnets and route tables in its report?

Thanks

**Comment by dhackney** [comment]
The current version of the snapshot utility supports all services but not all commands. 

So, yes, it does support VPC, subnets, and route tables but with some important caveats.

Note that not all services have been tested. 

The current version supports a limited set of single-parameter recursive commands and zero multi-parameter recursive commands. 

Recursive in this case meaning that the AWS CLI command parameter depends on the results of a prior AWS CLI command. 

No dependent parameter:
iam list-groups

Single parameter recursive: 
iam get-group --group-name workers


I'm currently updating this utility to support all single-parameter, multi-parameter, and prior-results-dependent AWS CLI commands for all services. 

I should have the initial v2 release supporting recursive-single-parameter up within a week or so. 

The following has been tested: 

#
###############################################################################
#

# VPC related ec2 commands 

ec2 describe-customer-gateways
ec2 describe-dhcp-options
ec2 describe-egress-only-internet-gateways
ec2 describe-internet-gateways
ec2 describe-nat-gateways
ec2 describe-network-acls
ec2 describe-route-tables
ec2 describe-subnets
ec2 describe-vpc-classic-link
ec2 describe-vpc-classic-link-dns-support
ec2 describe-vpc-endpoint-services
ec2 describe-vpc-endpoints
ec2 describe-vpc-peering-connections

# the following command returns both VPC and EC2 classic security groups
# need to add this filter: ec2 describe-security-groups --filters Name=vpc-id,Values=vpc*
ec2 describe-security-groups
# the following will return an error for an EC2 classic, non-VPC security group
@ec2 describe-security-group-references --group-id GroupId 
 
ec2 describe-vpcs
@ec2 describe-stale-security-groups --vpc-id VpcId

# the following require support for the 'attribute' parameter
#@ec2 describe-vpc-attribute --attribute enableDnsSupport --vpc-id VpcId
#@ec2 describe-vpc-attribute --attribute enableDnsHostnames --vpc-id VpcId
 
ec2 describe-vpn-connections
ec2 describe-vpn-gateways

#
###############################################################################
#

**Comment by vr00n** [comment]
Thank you much!
